version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies:
    only:
    - CacheBucket.Tests
deploy:
- provider: NuGet
  api_key:
    secure: nA9huQI+uilaKbaO0NQyUlAvsYIMVSEfpJoluxL2cd73zhv/husrMl7vVobhzCdp
  skip_symbols: false
  on:
    branch: master