version: '1.0.{build}'
dotnet_csproj:
  patch: true
  file: '.\CacheBucket\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
deploy:
  provider: NuGet
  api_key:
    secure: 2yfVmHju7K+xRwIdZZDCgcI2biJLyE7Etqha9cMm6NjXW+bUxGX3JwlZbYYsB9A4
  skip_symbols: false
  artifact: /.*\.nupkg/