version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
- ps: >-
    dotnet restore ./CacheBucket/CacheBucket.sln

    dotnet build ./CacheBucket/CacheBucket.sln

    dotnet pack ./CacheBucket/CacheBucket.sln
test:
  assemblies:
    only:
    - CacheBucket.Tests
deploy:
- provider: NuGet
  api_key:
    secure: nA9huQI+uilaKbaO0NQyUlAvsYIMVSEfpJoluxL2cd73zhv/husrMl7vVobhzCdp
  skip_symbols: false
  on:
    branch: master